### ISSUE TITLE
homebrew cask

### ISSUE THREAD

**Issue by avoidik** [claudiodekker/ungoogled-chromium-macos#4]
hey,

would it be possible for you to create a homebrew cask for it? there is something I've created, perhaps you'd want to manage that closer to the source (meaning your repo)?

https://github.com/avoidik/homebrew-eloston-chromium-signed?tab=readme-ov-file

cheers

**Comment by 3Samourai** [comment]
+1

**Comment by claudiodekker** [comment]
Hey @avoidik,

I currently don't have time for this (sorry!), but feel free to publish this yourself, I don't mind! :)

One note, though, is that over time, there is a chance that this repo [might be deprecated in favor of officially signed builds](https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/179#issuecomment-2267129871) from @Cubik65536 over the long term.

Thanks!

**Comment by avoidik** [comment]
xref. https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/184
